### ISSUE TITLE
Shortcuts for MacOS

### ISSUE THREAD

**Issue by jusech5** [EliMirren/Eclipse-Multiple-Cursor#2]
What is the Shortcuts for MacOS? In the original project are Ctrl+G and Ctrl+Cmd+G https://github.com/caspark/eclipse-multicursor/blob/master/README.md#usage

**Comment by shenzhenMirren** [comment]
I'm only testing on Windows, not on Mac. It should be the same.
--------------------------------------------------------------------
Shortcut Key Description
    Choose all the same words (all) : Ctrl+Alt+F
        The cursor first selects all the words by pressing the shortcut key, enters the changes, and does not support the ss ss search SS where the two words are connected.
    Choose the next same word (next, next): Ctrl + Alt + D
        The cursor first selects the word and presses the shortcut key to select the next identical word. Enter the change. It does not support the ss ss search with two words connected.
    Choose all the same words below (all remaining): Ctrl+Alt+N
        The cursor first selects the word and presses the shortcut key to select all the same words in the text. The input changes do not support the ss ss search for SS with two words connected.
    Custom Selection Location (Multiple Locations): Ctrl+Alt+V
        Press the shortcut key to mark the position to be inserted in the cursor selection
